- name: install dnsmasq
  package:
    name: dnsmasq
  become: true
- name: start dnsmasq
  systemd:
    name: dnsmasq
    state: started
    enabled: true
  become: true
- copy:
    dest: /etc/dnsmasq.d/test.conf
    content: |
      listen-address=192.168.123.4
      #server=10.11.5.19
      #server=10.5.30.160
      server=1.1.1.1
      server=8.8.8.8
      expand-hosts
      domain=test
      dhcp-option=6,192.168.123.4
      dhcp-range=192.168.123.5,192.168.123.50,12h
      dhcp-host={{ hostvars.vcenter.openstack.addresses.testlab[0]['OS-EXT-IPS-MAC:mac_addr'] }},vcenter,192.168.123.8
      local=/test/
  notify: restart dnsmasq
  become: true
- copy:
    dest: /etc/resolv.conf
    content: nameserver 192.168.123.4
  become: true
- name: add the host in /etc/hosts
  copy:
    dest: /etc/hosts
    content: |
      127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
      ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
      192.168.123.4  datastore
      192.168.123.6  esxi1
      192.168.123.7  esxi2
      192.168.123.8 vcenter
  become: true
  notify: restart dnsmasq
- meta: flush_handlers
